//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace QLRDemoUploader.com.qlranks.qlranksscanningengine {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QlranksScanningEngineServiceSoap", Namespace="http://qlranksScanningEngine.qlranks.com")]
    public partial class QlranksScanningEngineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UpdatePlayerOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadDemoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckDemoInMd5OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlayerEloOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QlranksScanningEngineService() {
            this.Url = global::QLRDemoUploader.Properties.Settings.Default.QLRDemoUploader_com_qlranks_qlranksscanningengine_QlranksScanningEngineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UpdatePlayerCompletedEventHandler UpdatePlayerCompleted;
        
        /// <remarks/>
        public event UploadDemoCompletedEventHandler UploadDemoCompleted;
        
        /// <remarks/>
        public event CheckDemoInMd5CompletedEventHandler CheckDemoInMd5Completed;
        
        /// <remarks/>
        public event GetPlayerEloCompletedEventHandler GetPlayerEloCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qlranksScanningEngine.qlranks.com/UpdatePlayer", RequestNamespace="http://qlranksScanningEngine.qlranks.com", ResponseNamespace="http://qlranksScanningEngine.qlranks.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdatePlayer(string playerName) {
            object[] results = this.Invoke("UpdatePlayer", new object[] {
                        playerName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePlayerAsync(string playerName) {
            this.UpdatePlayerAsync(playerName, null);
        }
        
        /// <remarks/>
        public void UpdatePlayerAsync(string playerName, object userState) {
            if ((this.UpdatePlayerOperationCompleted == null)) {
                this.UpdatePlayerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePlayerOperationCompleted);
            }
            this.InvokeAsync("UpdatePlayer", new object[] {
                        playerName}, this.UpdatePlayerOperationCompleted, userState);
        }
        
        private void OnUpdatePlayerOperationCompleted(object arg) {
            if ((this.UpdatePlayerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePlayerCompleted(this, new UpdatePlayerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qlranksScanningEngine.qlranks.com/UploadDemo", RequestNamespace="http://qlranksScanningEngine.qlranks.com", ResponseNamespace="http://qlranksScanningEngine.qlranks.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UploadDemo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] contents, string filename, string extention, int fileSizeBytes) {
            object[] results = this.Invoke("UploadDemo", new object[] {
                        contents,
                        filename,
                        extention,
                        fileSizeBytes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDemoAsync(byte[] contents, string filename, string extention, int fileSizeBytes) {
            this.UploadDemoAsync(contents, filename, extention, fileSizeBytes, null);
        }
        
        /// <remarks/>
        public void UploadDemoAsync(byte[] contents, string filename, string extention, int fileSizeBytes, object userState) {
            if ((this.UploadDemoOperationCompleted == null)) {
                this.UploadDemoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDemoOperationCompleted);
            }
            this.InvokeAsync("UploadDemo", new object[] {
                        contents,
                        filename,
                        extention,
                        fileSizeBytes}, this.UploadDemoOperationCompleted, userState);
        }
        
        private void OnUploadDemoOperationCompleted(object arg) {
            if ((this.UploadDemoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDemoCompleted(this, new UploadDemoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qlranksScanningEngine.qlranks.com/CheckDemoInMd5", RequestNamespace="http://qlranksScanningEngine.qlranks.com", ResponseNamespace="http://qlranksScanningEngine.qlranks.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckDemoInMd5(string md5OfDemo) {
            object[] results = this.Invoke("CheckDemoInMd5", new object[] {
                        md5OfDemo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckDemoInMd5Async(string md5OfDemo) {
            this.CheckDemoInMd5Async(md5OfDemo, null);
        }
        
        /// <remarks/>
        public void CheckDemoInMd5Async(string md5OfDemo, object userState) {
            if ((this.CheckDemoInMd5OperationCompleted == null)) {
                this.CheckDemoInMd5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckDemoInMd5OperationCompleted);
            }
            this.InvokeAsync("CheckDemoInMd5", new object[] {
                        md5OfDemo}, this.CheckDemoInMd5OperationCompleted, userState);
        }
        
        private void OnCheckDemoInMd5OperationCompleted(object arg) {
            if ((this.CheckDemoInMd5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckDemoInMd5Completed(this, new CheckDemoInMd5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://qlranksScanningEngine.qlranks.com/GetPlayerElo", RequestNamespace="http://qlranksScanningEngine.qlranks.com", ResponseNamespace="http://qlranksScanningEngine.qlranks.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPlayerElo(string playerName) {
            object[] results = this.Invoke("GetPlayerElo", new object[] {
                        playerName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlayerEloAsync(string playerName) {
            this.GetPlayerEloAsync(playerName, null);
        }
        
        /// <remarks/>
        public void GetPlayerEloAsync(string playerName, object userState) {
            if ((this.GetPlayerEloOperationCompleted == null)) {
                this.GetPlayerEloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlayerEloOperationCompleted);
            }
            this.InvokeAsync("GetPlayerElo", new object[] {
                        playerName}, this.GetPlayerEloOperationCompleted, userState);
        }
        
        private void OnGetPlayerEloOperationCompleted(object arg) {
            if ((this.GetPlayerEloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlayerEloCompleted(this, new GetPlayerEloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdatePlayerCompletedEventHandler(object sender, UpdatePlayerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePlayerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePlayerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UploadDemoCompletedEventHandler(object sender, UploadDemoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDemoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDemoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CheckDemoInMd5CompletedEventHandler(object sender, CheckDemoInMd5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckDemoInMd5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckDemoInMd5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPlayerEloCompletedEventHandler(object sender, GetPlayerEloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlayerEloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlayerEloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591